import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Trash2 } from "lucide-react";
import { toast } from "react-hot-toast";
import api from "../api/axios";
import { getStoreUrl } from "../utils/storeUrl";

function StoreDashboard() {
  const [store, setStore] = useState(null); const [products, setProducts] = useState([]); const [catalog, setCatalog] = useState([]); const [loading, setLoading] = useState(true);
  const load = async () => { try { const [storeResponse, productsResponse, catalogResponse] = await Promise.all([api.get("/dropshippers/me"), api.get("/dropshippers/products"), api.get("/product/all?limit=100")]); setStore(storeResponse.data.store); setProducts(productsResponse.data.products || []); setCatalog(catalogResponse.data.products || []); } catch (error) { toast.error(error?.response?.data?.message || "Unable to load dashboard"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const add = async (product) => { const price = window.prompt("Selling price", String(product.salePrice || product.price || 0)); if (price === null) return; try { await api.post("/dropshippers/products", { productId: product._id, sellingPrice: Number(price) }); toast.success("Added to your store"); load(); } catch (error) { toast.error(error?.response?.data?.message || "Unable to add product"); } };
  const remove = async (id) => { try { await api.delete(`/dropshippers/products/${id}`); setProducts(products.filter((item) => item._id !== id)); } catch { toast.error("Unable to remove product"); } };
  if (loading) return <main className="p-10 text-center text-gray-500">Loading dashboard...</main>;
  if (!store) return <main className="mx-auto max-w-xl px-4 py-16 text-center"><h1 className="text-3xl font-black">Start dropshipping</h1><Link className="mt-5 inline-block rounded-xl bg-blue-600 px-5 py-3 font-bold text-white" to="/create-store">Create your store</Link></main>;
  const selected = new Set(products.map((item) => item.product?._id));
  return <main className="mx-auto max-w-6xl px-4 py-10"><div className="mb-8 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-bold text-blue-600">Store dashboard</p><h1 className="mt-1 text-3xl font-black">{store.storeName}</h1><a className="text-sm font-bold text-blue-600" href={getStoreUrl(store.storeSlug)}>{getStoreUrl(store.storeSlug)}</a></div><Link to={`/store/${store.storeSlug}`} className="rounded-xl border px-4 py-2 text-center font-bold">View store</Link></div><section className="mb-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-blue-600 p-5 text-white"><p className="text-sm opacity-80">Selected products</p><strong className="text-3xl">{products.length}</strong></div><div className="rounded-2xl border p-5"><p className="text-sm text-gray-500">Store slug</p><strong>{store.storeSlug}</strong></div><div className="rounded-2xl border p-5"><p className="text-sm text-gray-500">Status</p><strong className="capitalize">{store.status}</strong></div></section><div className="grid gap-8 lg:grid-cols-2"><section><h2 className="mb-4 text-xl font-black">My products</h2>{products.length ? <div className="space-y-3">{products.map((item) => <div key={item._id} className="flex items-center justify-between rounded-xl border p-4"><span className="font-bold">{item.product?.name || "Product"}<small className="ml-3 text-gray-500">₹{item.sellingPrice}</small></span><button title="Remove product" onClick={() => remove(item._id)} className="text-red-500"><Trash2 size={18} /></button></div>)}</div> : <p className="rounded-xl border border-dashed p-8 text-center text-gray-500">No products selected yet.</p>}</section><section><h2 className="mb-4 text-xl font-black">Add from catalog</h2><div className="space-y-3">{catalog.filter((item) => !selected.has(item._id)).slice(0, 20).map((product) => <div key={product._id} className="flex items-center justify-between rounded-xl border p-4"><span className="truncate font-bold">{product.name}</span><button onClick={() => add(product)} className="ml-3 shrink-0 rounded-lg bg-blue-600 px-3 py-2 text-sm font-bold text-white">Add</button></div>)}</div></section></div></main>;
}

export default StoreDashboard;